import React from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ScrollText, ShieldCheck } from 'lucide-react';

const Terms = () => {
    const navigate = useNavigate();

    return (
        <div className="min-h-screen bg-[#0f172a] text-slate-200 pt-20 pb-20 px-6">
            <div className="max-w-4xl mx-auto">
                <button 
                    onClick={() => navigate(-1)} 
                    className="flex items-center gap-2 text-indigo-400 hover:text-indigo-300 mb-8 transition-colors group"
                >
                    <ArrowLeft size={20} className="group-hover:-translate-x-1 transition-transform" />
                    Back
                </button>

                <div className="glass p-8 md:p-12 rounded-[2.5rem] border border-white/10 shadow-2xl relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-600/10 blur-[100px] rounded-full"></div>
                    
                    <div className="relative z-10">
                        <div className="flex items-center gap-4 mb-8">
                            <div className="w-12 h-12 bg-indigo-500/20 rounded-2xl flex items-center justify-center">
                                <ScrollText className="text-indigo-400" />
                            </div>
                            <h1 className="text-3xl md:text-4xl font-black text-white">Terms of Service</h1>
                        </div>

                        <div className="space-y-8 text-slate-300 leading-relaxed">
                            <section>
                                <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                                    <ShieldCheck size={18} className="text-indigo-400" />
                                    Article 1 (Applicability)
                                </h2>
                                <p>
                                    These Terms of Service (the "Terms") govern the conditions of use for the Japanese learning service "Verba" (the "Service") provided by Aki Labs (the "Operator"). By accessing or using the Service, users agree to be bound by these Terms.
                                </p>
                            </section>

                            <section>
                                <h2 className="text-xl font-bold text-white mb-4">Article 2 (Founder's Pass and Payments)</h2>
                                <ul className="space-y-4 list-disc list-inside">
                                    <li>Users may access Pro account features (Founder's Pass) by paying the specified fee ($109.99/year).</li>
                                    <li>Subscriptions will automatically renew. To avoid being charged for the next billing cycle, users must cancel their subscription before the next renewal date.</li>
                                    <li>Due to the nature of digital content, as a general rule, no refunds or cancellations are accepted after payment is completed.</li>
                                </ul>
                            </section>

                            <section>
                                <h2 className="text-xl font-bold text-white mb-4">Article 3 (VRB Rewards)</h2>
                                <ul className="space-y-4 list-disc list-inside">
                                    <li>"VRB" granted within the Service is currently a digital reward (in-app point) usable strictly within the Service. It does not constitute a crypto asset (cryptocurrency) or any prepaid payment instrument.</li>
                                    <li>The Operator reserves the right to invalidate or extinguish the VRB held by users without prior compensation for any reason, including but not limited to the termination or modification of the Service, or user account suspension.</li>
                                    <li>The Operator may, in the future and at its sole discretion, provide certain benefits or transition/grant new tokens using blockchain technology (e.g., airdrops) to users holding VRB. However, the Operator does not legally guarantee or commit to providing any such future value or services.</li>
                                </ul>
                            </section>

                            <section>
                                <h2 className="text-xl font-bold text-white mb-4">Article 4 (AI-Generated Content Disclaimer)</h2>
                                <ul className="space-y-4 list-disc list-inside">
                                    <li>Some quizzes and explanations within the Service are automatically generated by Artificial Intelligence (AI).</li>
                                    <li>While the Operator strives for accuracy based on professional teaching data, the Operator makes no warranties regarding the complete accuracy, currency, usefulness, or non-infringement of the AI-generated content. Users shall use such content at their own risk.</li>
                                </ul>
                            </section>

                            <section>
                                <h2 className="text-xl font-bold text-white mb-4">Article 5 (Direct Lesson Booking Feature)</h2>
                                <ul className="space-y-4 list-disc list-inside">
                                    <li>Users may book online lessons with registered teachers (including Aki as a test case) through the Service.</li>
                                    <li>Cancellations or rescheduling must be made at least [24] hours prior to the scheduled lesson time. Cancellations made after this deadline will incur a designated cancellation fee (or the loss of lesson credits).</li>
                                </ul>
                            </section>

                            <section>
                                <h2 className="text-xl font-bold text-white mb-4">Article 6 (Prohibited Acts and Account Suspension)</h2>
                                <p className="mb-2">The Operator reserves the right to suspend or terminate a user's account without prior notice if the user engages in any of the following acts:</p>
                                <ul className="space-y-2 list-disc list-inside">
                                    <li>Acts that place an excessive load on the Service's systems or AI (e.g., spam, use of unauthorized automated scripts).</li>
                                    <li>Harassment, abusive behavior, or defamatory acts against other users or teachers.</li>
                                    <li>Any other acts deemed inappropriate by the Operator.</li>
                                </ul>
                            </section>

                            <section>
                                <h2 className="text-xl font-bold text-white mb-4">Article 7 (Disclaimer and Limitation of Liability)</h2>
                                <ul className="space-y-4 list-disc list-inside">
                                    <li>Unless caused by the Operator's willful misconduct or gross negligence, the Operator shall not be liable for any damages incurred by the user due to system failures, data loss, or the use of the Service.</li>
                                    <li>Even if the Operator is found liable to a user for damages for any reason, the Operator's total cumulative liability shall not exceed the total amount of fees paid by the user to the Operator for the Service in the past 12 months (e.g., the Founder's Pass purchase price).</li>
                                </ul>
                            </section>

                            <section>
                                <h2 className="text-xl font-bold text-white mb-4">Article 8 (Governing Law and Jurisdiction)</h2>
                                <p>
                                    These Terms shall be governed by and construed in accordance with the laws of Japan. Any disputes arising out of or in connection with the Service shall be subject to the exclusive jurisdiction of the Naha District Court in the first instance.
                                </p>
                            </section>
                        </div>

                        <div className="mt-12 pt-8 border-t border-white/5 text-center">
                            <p className="text-slate-500 text-sm">© 2026 VERBA TECHNOLOGIES. ALL RIGHTS RESERVED.</p>
                        </div>
                    </div>
                </div>
            </div>
            
            <style dangerouslySetInnerHTML={{ __html: `
                .glass {
                    background: rgba(255, 255, 255, 0.03);
                    backdrop-filter: blur(12px);
                    -webkit-backdrop-filter: blur(12px);
                }
            `}} />
        </div>
    );
};

export default Terms;
